### ISSUE TITLE
is it possible to overlay image to a building?

### ISSUE THREAD

**Issue by steve21124** [promet/PRAugmentedReality#17]
is it possible to overlay image to a building and the image still stay in that building even as the camera move around?

**Comment by glesage** [comment]
You mean like mask a building with an image? Anything is possible but it remains to be seen if it looks believable and fluid, etc...

You could replace one of the floating overlays by the image you want (all overlays are tagged).

Give me some more info if I misunderstood.

PS: I should ad that this is not a virtual reality framework, and it does not have image recognition or anything... its all off of location/accelerometer...

**Comment by steve21124** [comment]
Yes, you said it right. Masking a building with an image. And i agree to make it believable and fluid will be a challenge.  And no need image recognition, just overlay. The user will overlay image on top Augmented Reality probably as UIView and be able to move UIView in 3D direction. once the UIView Image position set, the image will overlay on Augmented Reality exactly on that position in reference to that buidling

**Comment by glesage** [comment]
Ok, well it'd be possible but you'd have to tweak the positioning of that overlay.

The overlays are shifted/moved to the left so that the tip of the arrow (and not the center) is exactly on the location...
Also the vertical positioning would have to be changed because currently they are displayed by order of distance/proximity from the user.

So if you changed those 2 things, as well as the size and content of an ARObject then yes it should work just fine.

**Comment by steve21124** [comment]
Great. Thanks for the tips
