### ISSUE TITLE
 Run 'pod install' or update your CocoaPods installation

### ISSUE THREAD

**Issue by karthikprabhuA** [promet/PRAugmentedReality#29]
Hi,
I am getting the following build error. please help me to build and run the app

diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

I followed the follwoing steps to install ipod
sudo gem install cocoapods
pod setup
cd PRAR-Example/
pod install

pasting terminal lines :-1: 
$Mac-mini:PRAR-Example cts$ pod install
Analyzing dependencies
Downloading dependencies
Installing AFNetworking (1.3.1)
Installing FMDB (2.1)
Installing SCNetworkReachability (1.2.0)
Generating Pods project
Integrating client project

[!] From now on use `PRAR-Example.xcworkspace`.

**Comment by glesage** [comment]
Hey,
I'm not too sure about this because this is more of a cocoapods issue, pretty weird...
I'd say, make sure you've got an updated version of ruby and clear any strange files (ones that are not in the github repo) you see in the directory if any /:

Also, make sure you quit Xcode before doing `pod install` and then make sure you do use that `PRAR-Example.xcworkspace` to open the app and not the original `PRAR-Example.xcodeproj`

**Comment by glesage** [comment]
Any updates on this?

**Comment by karthikprabhuA** [comment]
Really sorry for the late response.I giveup the try and currently using iPhone-AR-Toolkit. Thank you so much for your help

**Comment by nicolastinkl** [comment]
So. i get error info with that:
localhost:Home applepc$ pod install
Analyzing dependencies
/Library/Ruby/Gems/1.8/gems/cocoapods-0.26.2/lib/cocoapods/executable.rb:55: warning: Insecure world writable dir /usr/local in PATH, mode 040777
[!] Pod::Executable pull

fatal: No remote repository specified.  Please, specify either a URL or a

remote name from which new revisions should be fetched.
