### ISSUE TITLE
Camera View issue

### ISSUE THREAD

**Issue by ghost** [promet/PRAugmentedReality#40]
Great library! but I found a little problem.
I use Xcode 5 with IOS 7.
Showing camera view was worked at the first time, but when I back the previous view controller and then get into ARView again the camera view does not show again, but only a blank view.
Then I found that because these codes
dispatch_once(&onceToken, ^{
            _sharedManager = [[self alloc] initWithScreenSize:size withRadar:YES andDelegate:theDelegate];
        });
This init method only works once. is it ok If I move it out? or maybe lead some potential issues?

**Comment by glesage** [comment]
Well the manager is supposed to be a singleton but I guess there might be a problem with making the camera layer part of the singleton... thanks for pointing it out, I'll investigate! (:

**Comment by glesage** [comment]
Actually tested this but the camera does work as long as you reload your view and set the Camera layer as a sublayer

**Comment by faizandedia** [comment]
doesn't work, I tested and identified the issue because of the delegate method, you passing the delegate in init method for the first time  because it is singleton than the second time delegate is not set. you have to set delegate property again in order to receive the delegate events. :)

[[PRARManager sharedManager]setDelegate:self]; // set in in ViewDidLoad every time

Also, there were some more issues when you launch it on second time.I have fixed those. will share code with you soon.

**Comment by glesage** [comment]
Oh alright my bad, thanks a lot for the info @faizandedia, I'll also look into it!

**Comment by trungnv2** [comment]
hello, I got exactly that problem when I launch it on second time, so,I wonder if is anything changes to fix that? Thanks so much with your helps.

**Comment by xavierjurado** [comment]
This issue should be fixed in #45 @legendstar177. Feel free to review our pull requests and use our fork until the changes are merged back!
